[[headers]]
  for = "/*"
  [headers.values]
    X-Clacks-Overhead = "GNU Terry Pratchett"


[[redirects]]
  from = "/register/renew/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=renew"
  status = 301
  force = true


[[redirects]]
  from = "/register/trial/joey/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=rego&membership=404850"
  status = 301
  force = true

[[redirects]]
  from = "/register/trial/cub/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=rego&membership=404853"
  status = 301
  force = true

[[redirects]]
  from = "/register/trial/scout/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=rego&membership=404854"
  status = 301
  force = true

[[redirects]]
  from = "/register/trial/venturer/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=rego&membership=404851"
  status = 301
  force = true


[[redirects]]
  from = "/register/new/joey/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=rego&membership=404846"
  status = 301
  force = true

[[redirects]]
  from = "/register/new/cub/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=rego&membership=404847"
  status = 301
  force = true

[[redirects]]
  from = "/register/new/scout/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=rego&membership=404848"
  status = 301
  force = true

[[redirects]]
  from = "/register/new/venturer/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=rego&membership=404849"
  status = 301
  force = true


[[redirects]]
    from = "/register/new/adult/"
    to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=rego&membership=404852"
    status = 301
    force = true

  [[redirects]]
    from = "/register/new/leader/"
    to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=rego&membership=412441"
    status = 301
    force = true


[[redirects]]
    from = "/register/"
    to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh"
    status = 301
    force = true


[[redirects]]
  from = "/sc-minutes/"
  to = "https://nswscouts-my.sharepoint.com/:f:/g/personal/toby_griffin_nsw_scouts_com_au/Em4q9ozFJd9NucpgqRdikegBdzsGyaJoyQBKmsEKyZWQFA"
  status = 301
  force = true
