[[headers]]
  for = "/*"
  [headers.values]
    X-Clacks-Overhead = "GNU Terry Pratchett"

[[redirects]]
  from = "/register/"
  to = "https://www.1st-blackheath.group.scoutsnsw.com.au/registration/"
  status = 301
  force = true
