[[headers]]
  for = "/*"
  [headers.values]
    X-Clacks-Overhead = "GNU Terry Pratchett"


[[redirects]]
  from = "/register/trial/joey/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&membership=344323"
  status = 301
  force = true

[[redirects]]
  from = "/register/trial/cub/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&membership=344324"
  status = 301
  force = true

[[redirects]]
  from = "/register/trial/scout/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&membership=344325"
  status = 301
  force = true

[[redirects]]
  from = "/register/trial/venturer/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&membership=344330"
  status = 301
  force = true


[[redirects]]
  from = "/register/new/adult/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&membership=341847"
  status = 301
  force = true

[[redirects]]
  from = "/register/new/leader/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&membership=341848"
  status = 301
  force = true

[[redirects]]
  from = "/register/new/joey/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&membership=341843"
  status = 301
  force = true

[[redirects]]
  from = "/register/new/cub/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&membership=341844"
  status = 301
  force = true

[[redirects]]
  from = "/register/new/scout/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&membership=341845"
  status = 301
  force = true

[[redirects]]
  from = "/register/new/venturer/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&membership=341846"
  status = 301
  force = true


[[redirects]]
    from = "/register/"
    to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh"
    status = 301
    force = true
[[redirects]]
    from = "/register/active-creative-kids/"
    to = "https://www.scoutsnsw.com.au/voucher-redemption/"
    status = 301
    force = true
[[redirects]]
    from = "/register/payment-plan/"
    to = "https://forms.office.com/pages/responsepage.aspx?id=S7vnQHd2UEyzs2vwJ_MecbUWdmNH17VKqMPYErytB-ZUNVk1VDZXRU9CWkc3M083UlpKRlc5RllOSi4u"
    status = 301
    force = true


[[redirects]]
  from = "/sc-minutes/"
  to = "https://nswscouts-my.sharepoint.com/:f:/g/personal/toby_griffin_nsw_scouts_com_au/Em4q9ozFJd9NucpgqRdikegBdzsGyaJoyQBKmsEKyZWQFA"
  status = 301
  force = true
