[[headers]]
  for = "/*"
  [headers.values]
    X-Clacks-Overhead = "GNU Terry Pratchett"

# TRIAL

[[redirects]]
  from = "/register/trial/joey/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=rego&membership=509201"
  status = 301
  force = true

[[redirects]]
  from = "/register/trial/cub/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=rego&membership=509199"
  status = 301
  force = true

[[redirects]]
  from = "/register/trial/scout/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=rego&membership=509200"
  status = 301
  force = true

[[redirects]]
  from = "/register/trial/venturer/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=rego&membership=509197"
  status = 301
  force = true

# NEW

[[redirects]]
  from = "/register/new/joey/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=renew&membership=509193"
  status = 301
  force = true

[[redirects]]
  from = "/register/new/cub/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=renew&membership=509194"
  status = 301
  force = true

[[redirects]]
  from = "/register/new/scout/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=renew&membership=509195"
  status = 301
  force = true

[[redirects]]
  from = "/register/new/venturer/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=renew&membership=509196"
  status = 301
  force = true

[[redirects]]
  from = "/register/new/adult/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=rego&membership=509198"
  status = 301
  force = true

[[redirects]]
  from = "/register/new/leader/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=rego&membership=509204"
  status = 301
  force = true

# RENEW

[[redirects]]
    from = "/register/renew/joey/"
    to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=renew&membership=509191"
    status = 301
    force = true

[[redirects]]
  from = "/register/renew/cub/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=renew&membership=509188"
  status = 301
  force = true

[[redirects]]
  from = "/register/renew/scout/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=renew&membership=509189"
  status = 301
  force = true

[[redirects]]
  from = "/register/renew/venturer/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=renew&membership=509190"
  status = 301
  force = true

[[redirects]]
  from = "/register/renew/adult/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=renew&membership=509202"
  status = 301
  force = true

[[redirects]]
  from = "/register/renew/leader/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/rego/start/?fresh&proposed_mode=renew&membership=509203"
  status = 301
  force = true

# OTHER

[[redirects]]
  from = "/login/"
  to = "https://1st-blackheath.group.scoutsnsw.com.au/login"
  status = 301
  force = true
